spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 172.20.4.15
    port: 5672
    username: guest
    password: guest
  redis:
    host: 172.20.4.15
    port: 6379
  jpa:
    show-sql: true
girl: 18
